### ISSUE TITLE
Client install relies on a non-existent repository

### ISSUE THREAD

**Issue by tjesser-ucdavis-edu** [retrievertech/seismogram-app#1]
The bower install of the client relies on the git repository https://github.com/RedfishGroup/redfish-util that no longer exists. Is there some other location that could be used to retrieve that repository or is there some other library that supplies the same functionality?

Here is the error message:

```
bower redfish-util#*                   ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com:RedfishGroup/redfish-util.git", exit code of #128 Host key verification failed. fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

Additional error details:
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
The command '/bin/sh -c bower install' returned a non-zero code: 1
```

Here is the Dockerfile I've been using to establish the required dependencies:
```
FROM ubuntu:16.04

RUN apt update -y && apt install -y \
  build-essential \
  git \
  libcairo2-dev \
  libgif-dev \
  libjpeg-dev \
  libpango1.0-dev \
  librsvg2-dev \
  mongodb \
  nodejs \
  npm \
  pkg-config

RUN adduser \
  --quiet \
  seismo

RUN npm install \
  --global \
  bower

RUN ln -s \
  /usr/bin/nodejs \
  /usr/bin/node

USER seismo

WORKDIR /home/seismo

RUN git clone 'https://github.com/retrievertech/seismogram-app.git'

WORKDIR /home/seismo/seismogram-app/data-tools

RUN npm install

RUN nodejs jsonize.js

WORKDIR /home/seismo/seismogram-app/server

RUN sed --in-place 's/"canvas": .*$/"canvas": "^1.2",/' 'package.json'

RUN npm install

WORKDIR /home/seismo/seismogram-app/client

RUN bower install
```

**Comment by bennlich** [comment]
Ah. Looks like that repo has been made private in the time that has passed. I'll look into this. Are you continuing the project?

**Comment by mariusnita** [comment]
I think it depends on that repo just for this leaflet convenience wrapper https://github.com/retrievertech/seismogram-app/blob/master/client/src/browse/StationMap.svc.js#L1 which is very lightly used.

I think you can get rid of that `redfish-util` dependency if you use just replace the `init` function here https://github.com/retrievertech/seismogram-app/blob/master/client/src/browse/StationMap.svc.js#L14 with this (note that I haven't tested this code):
```js
init(id) {
  this.leafletMap = new L.Map(id, {
    minZoom: 1,
    maxZoom: 5,
    maxBounds: [[-90, -180], [90, 180]]
  });
  L.control.scale().addTo(this.leafletMap);
  this.leafletMap.setView(new L.LatLng(0,0), 3);
  let baseLayer = new L.TileLayer("http://api.tiles.mapbox.com/v4/mapbox.light/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiYmVubmxpY2giLCJhIjoieUx\
HOHQyNCJ9.VLDDBTTdzeHKJvR5ABYaLA", {
    zIndex: 1,
    zoomAnimation: false,
    opacity: 0.4
  });
  this.leafletMap.addLayer(baseLayer);
  this.leafletMap.fire("baselayerchange", { layer: baseLayer });
}
```
and then also replace all occurrences of `this.map.leafletMap` in that file with `this.leafletMap`.

**Comment by tjesser-ucdavis-edu** [comment]
Thank you for the help. @mariusnita fix seems to have worked. I am able to finish the install and host the file with Apache, but there's an error about `traceur.js: ReferenceError: Options is not defined`.  It's probably unrelated to this issue, so I think this can be closed.

**Comment by mariusnita** [comment]
Cool. I can't tell of the top how that `Options` error could happen, maybe you can open another issue with details.
