### ISSUE TITLE
Saving attempt failed

### ISSUE THREAD

**Issue by retrievertech** [retrievertech/seismogram-app#11]
Editing of segments and meanlines followed by saving was successful.
After running the auto-assignment algorithm and editing the assignment, attempted saving the data gave 'saving attempt failed'
Developer tools show multiple errors, I'm not sure if only the last is relevant, but here's a couple of lines:
server responded with a status of 500 (Internal Server Error)
:3000/processing/save/061178_1234_0084_04.png:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/#/edit/061178_1234_0084_04.png:1 Uncaught (in promise) Object
:3000/processing/save/061178_1234_0084_04.png:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
:3000/processing/save/061178_1234_0084_04.png:1          Failed to load resource: the server responded with a status of 500 (Internal Server Error)
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND

**Comment by bennlich** [comment]
This should be fixed now. Give it a go and let me know if you have any issues.
