### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by retrievertech** [retrievertech/seismogram-app#13]
Took too long to respond

**Comment by bennlich** [comment]
Hmm. Investigating. Was this correlated to you trying to run any auto-assignments? Maybe the instance size is too small.

**Comment by bennlich** [comment]
Looking at /var/syslog, I see a bunch out of memory issues (followed by network connectivity issues, which explains the timeout). I'm going to try increasing the size of the instance.

**Comment by bennlich** [comment]
I upgraded from t2.small to t2.medium. Site is back up, so I'll close this issue, but I'll open another one about monitoring memory usage to make sure there's no leak.
