### ISSUE TITLE
Edited counter doesn't increment

### ISSUE THREAD

**Issue by retrievertech** [retrievertech/seismogram-app#15]
Editing and saving does not change the count when in all-stations list view.
Newly edited seismo shows up in map and list view only when selecting the specific station in map view.
Count doesn't increment, and doesn't agree with number of images displayed in list view.
However, some edited seismos showed up in list and map view, and count did increment, a day or two after editing.  So it's a bit of a puzzle.

**Comment by bennlich** [comment]
Fixed in https://github.com/retrievertech/seismogram-app/commit/763664218ac25456e27a20bb7d3cafad5dfebadc
