### ISSUE TITLE
Can't download original

### ISSUE THREAD

**Issue by retrievertech** [retrievertech/seismogram-app#4]
I was trying to download an original file using the 'download original' button in the viewer, but it doesn't seem to be responding.  It doesn't work regardless if I'm logged in or not.  Tried on a couple of different Win10 computers. 
Using Chrome, Version 72.0.3626.81 (Official Build) (64-bit)
Also tried it on Microsoft Edge which also didn't respond.
I'll paste in the console log below.  It didn't preserve formatting, so this is a screen shot.
![console](https://user-images.githubusercontent.com/8988120/52309957-f1afb680-295e-11e9-95f0-0f0d75eaa77a.jpg)

**Comment by bennlich** [comment]
Hey, Andy. Should be fixed now. Try a hard refresh to clear your cache. Marius fixed this on master, but it wasn't deployed yet. (p.s. the errors in your console are unrelated)

**Comment by retrievertech** [comment]
Got it, downloads properly.  Thanks!
